# Generated by Django 5.2.6 on 2025-09-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
