# Generated by Django 5.2.6 on 2025-09-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_activationtoken_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_target',
            new_name='target_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
