# Generated by Django 5.2.6 on 2025-09-10 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_project_category_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpicture',
            options={'ordering': ['-is_primary', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='projectpicture',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
