# Generated by Django 5.2.6 on 2025-09-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_projectpicture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
