# Generated by Django 5.2.6 on 2025-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('coming soon', 'Coming Soon'), ('active', 'Active'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
