# Generated by Django 5.2.6 on 2025-09-13 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01XXXXXXXXX'. 11 digits allowed.", regex='^01[0-2,5]{1}[0-9]{8}$')], verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('active', 'Active'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
